# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: QodanaScan@2022
  inputs:
    args: '--linter,jetbrains/qodana-js:latest,--log-level,debug,-e,QODANA_BRANCH=$(Build.SourceBranchName),-e,QODANA_REMOTE_URL=$(Build.Repository.Uri)'
